### ISSUE TITLE
Cannot read property 'src' of null

### ISSUE THREAD

**Issue by pvtulsiram538** [ffalt/pdf.js-extract#1]
TypeError: Cannot read property 'src' of null
    at D:\Projects\PPT-PDF\ppt-pdf\node_modules\pdfjs-dist-for-node\build\pdf.combined.js:44786:53
    at Object.<anonymous> (D:\Projects\PPT-PDF\ppt-pdf\node_modules\pdfjs-dist-for-node\build\pdf.combined.js:
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Projects\PPT-PDF\ppt-pdf\node_modules\pdf.js-extract\lib\pdf-extract.js:15:16)

**Comment by pvtulsiram538** [comment]
I  solved the  issue by adding   below code at line number 44786 
var pdfjsSrc = scriptTagContainer.lastChild ==null ? 
    null : scriptTagContainer.lastChild.src;

and removed this below line
 var pdfjsSrc = scriptTagContainer.lastChild.src
