### ISSUE TITLE
Error after build for util.js

### ISSUE THREAD

**Issue by dalbir** [ffalt/pdf.js-extract#23]
(node:32392) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '//../base/shared/util.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at D:\Users\DSingh69\MyWork\ProjectsCode\NELP\CART_T\API\dist\index.js:341:847420
    at Array.forEach (<anonymous>)

**Comment by dalbir** [comment]
Not related to this package. Sorry
