### ISSUE TITLE
Error when using library in a serverless function, bundled via webpack

### ISSUE THREAD

**Issue by florianbepunkt** [ffalt/pdf.js-extract#26]
I try to use this library in a project that is deployed to AWS lambda. The code is bundled via webpack (serverless-webpack). While executing I get the following error:

```
ERROR	webpack://herakles/node_modules/pdf.js-extract/lib/pdfjs/pdf.js:14614
          _this10._readyCapability.reject(new Error("Setting up fake worker failed: \"".concat(reason.message, "\".")));
                                          ^

Error: Setting up fake worker failed: "Cannot find module './pdf.worker.js'
Require stack:
- /var/task/src/verify-pdf.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js".
    at null.<anonymous> (webpack://herakles/node_modules/pdf.js-extract/lib/pdfjs/pdf.js:14614:43)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by florianbepunkt** [comment]
@ffalt I excluded pdf.js-extract from the bundling process which made the error go away.

**Comment by mr-chandan** [comment]
@florianbepunkt can you share how you did this, I am new to this stuff it will help a lot

Thank you
